"use client"

import "@/app/globals.css"
import Head from "next/head"

import { Sidebar, Topbar } from "@/components/organisms"
import { getCookie } from "cookies-next"
import AuthLogin from "../(auth)/auth/login/page"
import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
export const metadata = {
  title: "Nija Dashboard",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico"
  }
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const router = useRouter()

  const [mount, setMount] = useState<Bolean|null>(null)

  useEffect(() => {
    if (getCookie("access_token")) {
      setMount(true)
    }

    if (!getCookie("access_token")) {
      setMount(false)
    }

    {
      console.log("access_sadsasadtoken")
    }
  }, [router])
  // if (getCookie("access_token")) {

  if (mount) {
    return (
      <html lang='en'>
        <Head>
          <link rel='shortcut icon' href='/favicon.ico' type='image/x-icon' />
        </Head>
        <body className={`UI-Ecommerce`}>
          <div className='fixed left-0 top-0 z-10 w-64 2xl:w-72'>
            <Sidebar />
          </div>

          <div className='fixed inset-0 z-10 ml-64 h-20 w-[calc(100vw_-_256px)] 2xl:ml-72 2xl:w-[calc(100vw_-_288px)]'>
            <Topbar />
          </div>

          <main className='relative z-0 min-h-screen bg-netral-20/50 pl-64 pt-20 2xl:pl-72'>
            {children}
          </main>
        </body>
      </html>
    )
  }


  if(mount ==null){
    return (
      <html lang='en'>
        <body className={`UI-Ecommerce`}>
          <main className='relative z-0 min-h-screen bg-netral-20/50 pl-64 pt-20 2xl:pl-72'>
    loading.....
          </main>
        </body>
      </html>
    )
  }

  
  return (
    <html lang='en'>
      <body className={`UI-Ecommerce`}>
        <main className='relative z-0 min-h-screen bg-netral-20/50 pl-64 pt-20 2xl:pl-72'>
   <AuthLogin/>
        </main>
      </body>
    </html>
  )

}

//   return (
//     <html lang='en'>
//       <body className={`UI-Ecommerce`}>
//         <AuthLogin />
//       </body>
//     </html>
//   )
// }
